### ISSUE TITLE
Azure DevOps badge shows red

### ISSUE THREAD

**Issue by bvulpes-seaworld** [DataDog/datadog-ci-azure-devops#35]
![Screenshot 2023-01-31 at 8 56 26 AM](https://user-images.githubusercontent.com/76780891/215829967-1c04c728-854f-470d-93e6-16f00d666c7f.png)

Perhaps because your ADO repository is private, people outside your org can't get its status, and the badge goes red?

Bringing it up because it added a bit of friction in our org when we wanted to start experimenting with it.

**Comment by lefebvree** [comment]
Hello @bvulpes-seaworld, thank you for the heads-up we fixed the pipeline issue and are back to green.

**Comment by bvulpes-seaworld** [comment]
Thank you!
